### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by arthurvr** [hkalant/EducationalToolsResources#1]
Keep in mind that if you haven't selected a license, it basically means the people are not allowed to reproduce, distribute or create derivative works.

I would recommend CC0. Licenses like MIT, BSD, GPL, etc, are more for code.

**Comment by hkalant** [comment]
If by "reproduce, distribute or create derivative works" you mean "fork and add your own tools and resources", I think that I mentioned this in the introduction: "If you are familiar with Github, go star it, fork it and add your own tools of trade. It's hosted on Github for a reason. Please submit pull requests."

**Comment by arthurvr** [comment]
A quick sentence at the top of the readme isn't the same as a license. Though it does have *some* legal value, it's better to have one.

Side: check the [awesome manifesto](https://github.com/sindresorhus/awesome/blob/master/awesome.md) :)

**Comment by hkalant** [comment]
Thanks for bringing this to my attention @arthurvr. I believe that licenses are important.

To be honest, if you don't want to share the tools (by issuing a request) you have come across and you just want to fork the repo and add your own tools so that you can go back to your version whenever you like, it's fine. No problem with it.

But on the other hand, I wouldn't appreciate if you do fork it, add your own tools and build an audience and perhaps an audience larger than the original one. ;)

What kind of license do you recommend for a situation like this?

**Comment by arthurvr** [comment]
> What kind of license do you recommend for a situation like this?

CC0, but I'm an open source fanboy, not a lawyer. I can't give any real advice here. I honestly think a license for a list should just say "do whatever you like". In your case I would just copy-paste https://github.com/sindresorhus/awesome#license.

> But on the other hand, I wouldn't appreciate if you do fork it, add your own tools and build an audience and perhaps an audience larger than the original one. ;)

That sounds more limiting :cry: I don't think a license like that even exists. Though honestly, that's where open source is about. That kind of situations only happen when it's really needed, and generally it ends up being a good thing. And if somebody maintains a list better than I can do, I would actually love him/her to take that over. It's something else I don't have to maintain :p

**Comment by hkalant** [comment]
Alrighty. You convinced me. Thanks.
